[build]
  publish = "frontend/dist"
  command = "./build.sh"
  
# Clear cache on every deploy
[build.processing]
  skip_processing = false

# SPA routing - redirect only non-file requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Don't redirect if file exists
  force = false

[build.environment]
  NODE_VERSION = "18"

# Headers for caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"