-- PocketBase Database Schema for Employee Rewards System
-- This file documents the collections structure for PocketBase

-- Collection: users (extends PocketBase auth collection)
-- Additional fields for employee data
-- Fields:
-- - id (auto) - PocketBase user ID
-- - email (auto) - User email from auth
-- - name (text) - Full name
-- - employee_id (text) - Company employee ID
-- - department (text) - Employee department
-- - hire_date (date) - Employee hire date
-- - role (select) - employee, admin
-- - status (select) - active, inactive, pending
-- - points_balance (number) - Current points balance
-- - total_points_earned (number) - Lifetime points earned
-- - current_streak (number) - Current check-in streak
-- - longest_streak (number) - Best streak record
-- - created (auto) - Account creation date
-- - updated (auto) - Last update

-- Collection: check_ins
-- Daily employee check-in records
-- Fields:
-- - id (auto) - Unique check-in ID
-- - user_id (relation to users) - Employee who checked in
-- - check_in_time (datetime) - Exact check-in timestamp
-- - points_earned (number) - Points awarded for this check-in
-- - check_in_type (select) - early, ontime, late
-- - location (text, optional) - Check-in location/method
-- - streak_day (number) - Day number in current streak
-- - created (auto) - Record creation date
-- - updated (auto) - Last update

-- Collection: rewards
-- Available rewards catalog
-- Fields:
-- - id (auto) - Unique reward ID
-- - name (text) - Reward name
-- - description (text) - Reward description
-- - category (select) - weekly, monthly, quarterly, annual, special
-- - points_cost (number) - Points required to redeem
-- - quantity_available (number) - Available quantity (-1 for unlimited)
-- - is_active (bool) - Whether reward is currently available
-- - image_url (url, optional) - Reward image
-- - terms (text, optional) - Terms and conditions
-- - created (auto) - Creation date
-- - updated (auto) - Last update

-- Collection: redemptions
-- Reward redemption requests and history
-- Fields:
-- - id (auto) - Unique redemption ID
-- - user_id (relation to users) - Employee requesting redemption
-- - reward_id (relation to rewards) - Reward being redeemed
-- - points_spent (number) - Points deducted for redemption
-- - status (select) - pending, approved, rejected, fulfilled
-- - requested_date (datetime) - When redemption was requested
-- - processed_date (datetime, optional) - When admin approved/rejected
-- - processed_by (relation to users, optional) - Admin who processed
-- - rejection_reason (text, optional) - Reason for rejection
-- - fulfillment_notes (text, optional) - Notes about reward delivery
-- - created (auto) - Record creation date
-- - updated (auto) - Last update

-- Collection: badges
-- Achievement badges system
-- Fields:
-- - id (auto) - Unique badge ID
-- - name (text) - Badge name
-- - description (text) - Badge description
-- - icon (text) - Badge icon/emoji
-- - criteria_type (select) - streak, points, checkins, special
-- - criteria_value (number) - Value needed to unlock
-- - is_active (bool) - Whether badge is available
-- - created (auto) - Creation date
-- - updated (auto) - Last update

-- Collection: user_badges
-- User's earned badges
-- Fields:
-- - id (auto) - Unique record ID
-- - user_id (relation to users) - Employee who earned badge
-- - badge_id (relation to badges) - Badge earned
-- - earned_date (datetime) - When badge was earned
-- - created (auto) - Record creation date

-- Collection: motivational_quotes
-- Daily motivational messages
-- Fields:
-- - id (auto) - Unique quote ID
-- - quote_text (text) - The motivational quote
-- - author (text, optional) - Quote author
-- - category (select) - motivation, success, teamwork, general
-- - is_active (bool) - Whether quote is in rotation
-- - created (auto) - Creation date
-- - updated (auto) - Last update

-- Collection: system_settings
-- Application configuration
-- Fields:
-- - id (auto) - Unique setting ID
-- - setting_key (text) - Setting identifier
-- - setting_value (text) - Setting value (JSON string for complex values)
-- - description (text) - Setting description
-- - category (select) - points, timing, general, company
-- - created (auto) - Creation date
-- - updated (auto) - Last update

-- Initial System Settings:
-- - early_checkin_points: "2"
-- - ontime_checkin_points: "1" 
-- - late_checkin_points: "0"
-- - checkin_window_start: "06:00"
-- - checkin_window_end: "09:00"
-- - company_name: "System Kleen"
-- - timezone: "America/Denver" (MST)

-- Collection: point_transactions
-- Detailed points transaction history
-- Fields:
-- - id (auto) - Unique transaction ID
-- - user_id (relation to users) - Employee
-- - transaction_type (select) - earned, spent, adjusted, refunded
-- - points_amount (number) - Points (positive for earned, negative for spent)
-- - reference_type (select) - checkin, redemption, admin_adjustment, bonus
-- - reference_id (text) - ID of related record (check_in_id, redemption_id, etc)
-- - description (text) - Transaction description
-- - created_by (relation to users, optional) - Admin who created (for adjustments)
-- - created (auto) - Transaction date
-- - updated (auto) - Last update